FROM node:7

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . /usr/src/app
RUN npm install --only=production
RUN npm install pm2 -g

# replace this with your application's default port
EXPOSE 9100

CMD pm2-docker adservice.server.js
